Workbench-Frontend/application/data_blueprint/routes.py
from flask import Blueprint, render_template, request
from werkzeug.wrappers import Response
import requests as py_requests
import json

import config

# Blueprint Configuration
data_bp = Blueprint(
    'data_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@data_bp.route("/data-dashboard")
def dashboard():
    return render_template(
        "dashboard.html",
        title="Explore Data - Dashboard"
    )


@data_bp.route("/data/dashboard-data")
def get_dashboard_data():
    url = config.middleware + "db/evaluation_data"
    data = {}
    data_response = py_requests.get(url, data=data)
    content = data_response.content

    response = Response(content, status=200)
    return response


@data_bp.route("/data/recommendations", methods=['POST'])
def get_recommendations():
    visited_list = modified_list = fave_list = None
    if "visited_list" in request.form:
        visited_list = request.form["visited_list"]
    if "modified_list" in request.form:
        modified_list = request.form["modified_list"]
    if "fave_list" in request.form:
        fave_list = request.form["fave_list"]

    url = config.middleware + "db/recommendations"
    data = {
        "visited_list": visited_list,
        "modified_list": modified_list,
        "fave_list": fave_list
    }

    data_response = py_requests.post(url, data=data)
    content = data_response.content

    response = Response(content, status=200)
    return response


@data_bp.route("/data/generate-recommendation")
def generate_recommendation():
    return render_template(
        "user_gen_recommendation.html",
        title="Find a project like"
    )


@data_bp.route("/data/research_areas")
def get_research_areas():
    url_data = config.middleware + "esa/research_areas"
    data = {}
    data_response = py_requests.get(url_data, data=data)
    content = data_response.content

    response = Response(content, status=200)
    return response


@data_bp.route("/data/sdgs")
def get_sdgs():
    url_data = config.middleware + "esa/sdgs"
    data = {}
    data_response = py_requests.get(url_data, data=data)
    content = data_response.content

    response = Response(content, status=200)
    return response

Workbench-Frontend/application/data_blueprint/templates/recommendation.html
<div class="sidebar" id="mySidebar">
    <div>
        <button type="button" class="btn btn-light" id="close_sidebar" onclick="closeNav()">&#9776; Minimize</button>
        <br/>

        <span id="rec_descriptor"></span>
        <button type="button" class="btn" id="rec_help" data-toggle="tooltip" data-placement="right" title="More about recommendations">
            <i class="far fa-question-circle"></i>
        </button>
        <div id="recommendations"></div>
        <br><br>
        <span id="tba_descriptor"></span>
        <div id="projects-tba"></div>
    </div>
</div>


<script>
    $j = jQuery.noConflict();

    var showing_sidebar
    $j(document).ready(function (){
        init_recommendations()

        if ("showing_sidebar" in localStorage){
            showing_sidebar = localStorage["showing_sidebar"]
        } else {
            showing_sidebar = "true"
            localStorage["showing_sidebar"] = showing_sidebar
        }

        if (showing_sidebar === "true") {
            openNav()
        }

        $('[data-toggle="tooltip"]').tooltip();
    });

    function close_sidebar(){
        showing_sidebar = "false"
        localStorage["showing_sidebar"] = showing_sidebar
        const tba_node = document.getElementById("projects-tba");
        while (tba_node.firstChild) {
            tba_node.removeChild(tba_node.lastChild);
        }
        document.getElementById("tba_descriptor").innerText = ""

        document.getElementById("rec_descriptor").innerText = ""
            document.getElementById("rec_help").title = ""

        const rec_node = document.getElementById("recommendations");
        while (rec_node.firstChild) {
            rec_node.removeChild(rec_node.lastChild);
        }
    }

    function open_sidebar(){
        showing_sidebar = "true"
        localStorage["showing_sidebar"] = showing_sidebar
        get_recommendations(6, "recommendations")
        get_tba_projects()
    }

    function get_tba_projects(){
        if (!("tba_projects" in localStorage)){
            request_tba_projects(true)
        } else if (JSON.parse(localStorage["used_tba"]) > 1){
            request_tba_projects(true)
        } else{
            set_up_tba_projects()
        }
    }

    function set_up_suggestions(){
        if (!("tba_projects" in localStorage)){
            request_tba_projects(false)
        } else if (JSON.parse(localStorage["used_tba"]) > 1){
            request_tba_projects(false)
        } else {
            setup_project_name_field()
        }
    }

    function request_tba_projects(setup_tba){
        $j.get("/get-tba-projects").done(function (res){
            localStorage["tba_projects"] = res
            localStorage["used_tba"] = 0
            if (setup_tba) {
                set_up_tba_projects()
            } else {
                setup_project_name_field()
            }
        })
    }

    function set_up_tba_projects(){
        var tba_projects = JSON.parse(localStorage["tba_projects"])
        localStorage["used_tba"] = JSON.parse(localStorage["used_tba"]) + 1
        var random_start = Math.floor(Math.random()*tba_projects.length)
        var max = (5 < tba_projects.length) ? 5 : tba_projects.length
        for (var i=0; i<max; i++){
            var project = tba_projects[(random_start*(1+i))%tba_projects.length]
            var projectButton =document.createElement("button");
            projectButton.type = "button"
            projectButton.className = "project_button"
            projectButton.value = project
            projectButton.innerText = project
            projectButton.addEventListener('click', clicked_tba_project)
            document.getElementById("projects-tba").appendChild(projectButton);
        }
        if (max === 0){
            document.getElementById("tba_descriptor").innerText = "There are currently no unanalyzed Projects in the Database."
        } else {
            document.getElementById("tba_descriptor").innerText = "Help adding to the database and work on one of these projects:."
        }
    }

    function init_recommendations(){
        if(!("project_lists" in localStorage)){
            var project_lists = {
                "visited_list": [],
                "modified_list": [],
                "fave_list": []
            }
            localStorage["project_lists"] = JSON.stringify(project_lists)
            localStorage["changed_project_lists"] = true

        }
    }

    function get_recommendations(count_of_recommendations, table_div){
        if ("project_name" in localStorage) add_visited_project(localStorage["project_name"])
        if ("recommendations" in localStorage && localStorage["changed_project_lists"] === "false"){
            var res = JSON.parse(localStorage["recommendations"])
            var recommendations = []
            if (res.length < count_of_recommendations){
                count_of_recommendations = res.length
            }
            for (var i=0; i<count_of_recommendations; i++){
                recommendations.push(res[i][0])
            }
            update_recommendations(recommendations, table_div)
        }else{
            console.log("getting new recommendations")
            new_recommendations(count_of_recommendations, table_div)
        }

    }

    function update_recommendations(recommendations, div_id){
        var project_lists = JSON.parse(localStorage["project_lists"])
        var visited_list = project_lists["visited_list"]

        if (!(recommendations.length >0)) {
            document.getElementById("rec_descriptor").innerText = "There are currently no projects in the database."
            document.getElementById("rec_help").title = "Once there are projects in the database this is were recommendations of interesting projects will be displayed"
        }
        else if (visited_list.length>0) {
            document.getElementById("rec_descriptor").innerText = "Projects you might be interested in based on the projects you visited:"
            document.getElementById("rec_help").title = "These Recommendations are based on the projects you visited and those you analyzed of modified."
        }
        else {
            document.getElementById("rec_descriptor").innerText = "Projects you might be interested in:"
            document.getElementById("rec_help").title = "For now these ar general recommendations, personalized recommendations will be made as soon as you start looking at individual projects."
        }

        $('#rec_help').tooltip('enable')

        show_recommendations(recommendations, div_id)

    }

    function show_recommendations(recommendations, div_id){
        recommendations.forEach(function(rec){
            var projectButton =document.createElement("button");
            projectButton.type = "button"
            projectButton.value = rec
            projectButton.className = "project_button"
            projectButton.innerText = rec
            projectButton.addEventListener('click', clicked_project)
            document.getElementById(div_id).appendChild(projectButton);
        })
    }

    $j("#rec_help").click(function(){
        window.location.href = "{{url_for("explanation_bp.explanation_recommendation")}}"
    })

    var clicked_project = function(e){
        var project_name
        if (e.target.type === "button") {
            project_name = e.target.value
        } else {
            project_name = e.target.parentNode.value
        }

        navigate_to_analysed_project(project_name)
    }

    function navigate_to_analysed_project(project_name, new_window_or_tab=false){
        localStorage["project_name"] = project_name
        localStorage.removeItem("project-link")
        localStorage.removeItem("project-description")
        localStorage.removeItem("esa_res")
        localStorage.removeItem("sdg_res")
        localStorage.removeItem("ner_res")
        if (new_window_or_tab){
            window.open("/analyse/project")
        } else {
            window.location.href = "/analyse/project"
        }
    }

    var clicked_tba_project = function(e){
        var project_name
        if (e.target.type === "button") {
            project_name = e.target.value
        } else {
            project_name = e.target.parentNode.value
        }

        localStorage["project_name"] = project_name
        localStorage.removeItem("project-link")
        localStorage.removeItem("project-description")
        localStorage.removeItem("esa_res")
        localStorage.removeItem("sdg_res")
        localStorage.removeItem("ner_res")

        window.location.href = "/analyse"
    }

    function new_recommendations(count_of_recommendations, table_div){
        var project_lists = JSON.parse(localStorage["project_lists"])
        var visited_list = project_lists["visited_list"]
        var modified_list = project_lists["modified_list"]
        var fave_list = project_lists["fave_list"]
        $j.post("/data/recommendations", {"visited_list": JSON.stringify(visited_list), "modified_list":JSON.stringify(modified_list),
            "fave_list":JSON.stringify(fave_list)}).done(function (res){
            res = JSON.parse(res)["recommendations"]
            localStorage["recommendations"] = JSON.stringify(res)
            localStorage["changed_project_lists"] = false
            if (res.length < count_of_recommendations){
                count_of_recommendations = res.length
            }
            var recommendations = []
            for (var i=0; i<count_of_recommendations; i++){
                recommendations.push(res[i][0])
            }

            update_recommendations(recommendations, table_div)
        })
    }

    function add_visited_project(project){
        var project_lists = JSON.parse(localStorage["project_lists"])
        if (!(project_lists["visited_list"].includes(project))) {
            project_lists["visited_list"].push(project)
            localStorage["project_lists"] = JSON.stringify(project_lists)
            localStorage["changed_project_lists"] = true
        }
    }

    function add_modified_project(project){
        var project_lists = JSON.parse(localStorage["project_lists"])
        if (!(project_lists["modified_list"].includes(project))) {
            project_lists["modified_list"].push(project)
            localStorage["project_lists"] = JSON.stringify(project_lists)
            localStorage["changed_project_lists"] = true
        }
    }

    function add_fave_project(project){
        var project_lists = JSON.parse(localStorage["project_lists"])
        if (!(project_lists["fave_list"].includes(project))){
            project_lists["fave_list"].push(project)
            localStorage["project_lists"] = JSON.stringify(project_lists)
            localStorage["changed_project_lists"] = true
        }

    }

    function setup_project_name_field(){
        $j.get("/get-project-names").done(function(res){
            project_names = JSON.parse(res)

            setup_project_names = project_names.sort(function (a,b){
                if (a < b) {return -1}
                else if (a > b) {return 1}
                return 0
            })

            if ("tba_projects" in localStorage) {
                var tba_projects = JSON.parse(localStorage["tba_projects"])
                setup_project_names = setup_project_names.concat(tba_projects)
            }

            for (var i=0; i<setup_project_names.length; i++){
                var project_name = document.createElement("option")
                project_name.value = setup_project_names[i]
                project_name.innerText = setup_project_names[i]
                document.getElementById("datalistOptions").appendChild(project_name);
            }
        })
    }
</script>

Workbench-Frontend/application/data_blueprint/templates/user_gen_recommendation.html
{% extends 'layout.html' %}
{% set active_page = 'recommendation' %}

{% block header %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
{% endblock %}

{% block content %}
    <div class="textblock">
        <h1>Find a project that is similar to ...</h1>
        <label class="input-group-text" for="like_project_input">Projects</label>
        <select multiple class="js-example-basic-multiple js-states form-control" id="like_project_input" name="projects[]">

        </select>

        <label class="input-group-text" for="like_research_area_input">Research Areas</label>
        <select multiple class="js-example-basic-multiple js-states form-control" id="like_research_area_input" name="research_areas[]">

        </select>

        <label class="input-group-text" for="like_sdg_input">SDGs</label>
        <select multiple class="js-example-basic-multiple js-states form-control" id="like_sdg_input" name="sdgs[]">

        </select>

        <div class="btn_row">
            <button type="button" class="btn btn_dark_cs btn_send" id="generate_recommendations">generate</button>
        </div>

        <div id="generated_recommendations_loading"></div>
        <div id="generated_recommendations" class="flexbox"></div>


    </div>

{% endblock %}

{% block script %}
    <script>
        $j = jQuery.noConflict();

        var current_recommendations = []
        var sdg_names

        $j(document).ready(function(){
            $j('.js-example-basic-multiple').select2({
                placeholder: "Type to search ...",
                width: 'resolve'
            });

            if ("sdg_names" in localStorage){
                sdg_names = JSON.parse(localStorage["sdg_names"])
            } else {
                $j.get("/analyse/project/sdg_names", {}).done(function (res){
                    localStorage["sdg_names"] = res
                    sdg_names = JSON.parse(res)
                })
            }

            $j.get("{{ url_for("data_bp.get_research_areas") }}").done(function(res){
                var research_areas = JSON.parse(res)

                research_areas = research_areas.sort(function (a,b){
                    if (a < b) {return -1}
                    else if (a > b) {return 1}
                    return 0
                })

                research_areas.forEach(function(ra){
                    var newOption = new Option(ra, ra, false, false);
                    $j("#like_research_area_input").append(newOption).trigger('change');

                    /*var ra_option = document.createElement("option")
                    ra_option.value = ra
                    ra_option.innerText = ra
                    document.getElementById("like_research_area_input").appendChild(ra_option);*/
                })
            })

            $j.get("{{ url_for("data_bp.get_sdgs") }}").done(function(res){
                var sdgs = JSON.parse(res)

                sdgs = sdgs.sort(function (a,b){
                    if (a < b) {return -1}
                    else if (a > b) {return 1}
                    return 0
                })

                sdgs.forEach(function(sdg){
                    var sdg_name = sdg
                    if (sdg_names !== null){
                        sdg_name = sdg_names[sdg]
                    }
                    var newOption = new Option(sdg_name, sdg, false, false);
                    $j("#like_sdg_input").append(newOption).trigger('change');
                })
            })

            $j.get("/get-project-names").done(function(res){
                var project_names = JSON.parse(res)

                project_names = project_names.sort(function (a,b){
                    if (a < b) {return -1}
                    else if (a > b) {return 1}
                    return 0
                })

                project_names.forEach(function(project){
                    var newOption = new Option(project, project, false, false);
                    $j("#like_project_input").append(newOption).trigger('change');
                    /*var project_option = document.createElement("option")
                    project_option.value = project
                    project_option.innerText = project
                    document.getElementById("like_project_input").appendChild(project_option);*/
                })
            })
        })

        $j('#generate_recommendations').click(function(){
            var project_list = $j('#like_project_input').select2('data');
            var ra_list = $j('#like_research_area_input').select2('data');
            var sdg_list = $j('#like_sdg_input').select2('data');
            var complete_list = []
            if (project_list !== undefined && project_list.length > 0){
                project_list.forEach(function(option){
                    if (option !== undefined){
                        complete_list.push(option['id'])
                    }
                })
            }
            if (ra_list !== undefined && ra_list.length > 0){
                ra_list.forEach(function(option){
                    if (option !== undefined){
                        complete_list.push(option['id'])
                    }
                })
            }
            if (sdg_list !== undefined && sdg_list.length > 0){
                sdg_list.forEach(function(option){
                    if (option !== undefined){
                        complete_list.push(option['id'])
                    }
                })
            }

            for (var i=current_recommendations.length; i>0; i--){
                var rec = current_recommendations.pop()
                var rec_card = document.getElementById(rec)
                document.getElementById(rec).parentNode.removeChild(rec_card)
            }
            loading("generated_recommendations_loading")

            $j.post("/data/recommendations", {"visited_list": JSON.stringify(complete_list)}).done(function(res){
                res = JSON.parse(res)["recommendations"]
                var count_of_recommendations = 10
                if (res.length < count_of_recommendations){
                    count_of_recommendations = res.length
                }
                endloading("generated_recommendations_loading")
                for (var i=0; i<count_of_recommendations; i++){
                    current_recommendations.push("recommended_card_" + i)
                    add_recommended_project_card(res[i][0], "recommended_card_" +  i, "generated_recommendations")
                    //recommendations.push(res[i][0])
                }
                //show_recommendations(recommendations, "generated_recommendations")
            })
        })

        function add_recommended_project_card(recommended, count, div_id){
            var card = document.createElement("div")
            card.className = "card bg-light p-3 m-1 card_no_wrap"
            card.id = count
            var paragraph = document.createElement("p")
            paragraph.innerText = recommended
            card.appendChild(paragraph)
            var button = document.createElement("button")
            button.type = "button"
            button.value = recommended
            button.className = "project_button btn btn-outline-secondary"
            button.innerText = "visit"
            button.addEventListener('click', clicked_project_new_tab)
            card.appendChild(button)
            document.getElementById(div_id).appendChild(card);
        }

        var clicked_project_new_tab = function(e){
        var project_name
        if (e.target.type === "button") {
            project_name = e.target.value
        } else {
            project_name = e.target.parentNode.value
        }

        navigate_to_analysed_project(project_name, true)
    }

    </script>
{% endblock %}